#include <exception>
using namespace std;

class Nowy_uzytkownik;
class System;
class Rejestracja;

class Rejestracja
{
public: Nowy_uzytkownik* _unnamed_nowy_u¿ytkownik_;
public: System* _unnamed_system__;

public: void sprawdzenie_has³a();

public: void utworzenie_karty();

public: void utworzenie_has³a();

public: void uzupe³nienie_danych();

public: Rejestracja();

public: void nadanie_id();
};