#include <exception>
#include <iostream>
using namespace std;

#include "Wypozyczenie.h"

void Wypozyczenie::zeskanujKsiazke()
{
	cout << "Wypozyczenie przebieglo pomyslnie." << endl;
	getchar(), getchar();
}

